version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/stats-ui"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        # only raise PRs for minor version and patch updates,
        # ignore all major version updates
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
