ARG PORT

# Node image to use
FROM node:24

WORKDIR /app

# Copy all files
COPY stats-ui/ .

# Install dependencies
RUN npm install

# Build the app
RUN npm run build

# Use environment substitution in the built index.html
RUN sed -i 's|%REACT_APP_ENV%|'${REACT_APP_ENV}'|g' build/index.html

# Install serve
RUN npm install -g serve

# Expose port
EXPOSE ${PORT}

# Start the application
ENTRYPOINT ["serve", "-s", "build"]