gcp_project_id          = "arxiv-production"
gcp_region              = "us-central1"
env                     = "PROD"
write_db_user           = "insertupdate"
write_db_pw_secret_name = "stats-db-insertupdate-pw"
write_db_instance       = "arxiv-production:us-central1:stats-db"
write_db_name           = "site_usage"