options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FUNCTION_NAME: "aggregate_hourly_downloads"
  _PUBSUB_NAME: "papers-downloaded-by-id-recently"
  _PATH_TO_SOURCE: "stats-functions/aggregate_hourly_downloads/src"

steps:
  # Deploy to Cloud Run
  - name: "google/cloud-sdk"
    id: Deploy
    entrypoint: gcloud
    args:
      [
        "functions",
        "deploy",
        "${_FUNCTION_NAME}",
        # "--retry",
        "--gen2",
        "--source",
        "${_PATH_TO_SOURCE}",
        "--runtime",
        "python311",
        "--region",
        "${_DEPLOY_REGION}",
        # "--trigger-topic",
        # "${_PUBSUB_NAME}",
        "--trigger-http",
        "--entry-point",
        "${_FUNCTION_NAME}",
        "--env-vars-file",
        "cicd/env.${_FUNCTION_NAME}.${PROJECT_ID}.yaml",
        "--allow-unauthenticated",
      ]
