apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: arxiv-stats-ui
spec:
  template:
    spec:
      containers:
        - image: gcr.io/arxiv-development/arxiv-stats-ui:latest
          env:
            - name: FE_PORT
              value: "9000"
          resources:
            limits:
              memory: 1G
