gcp_project_id       = "arxiv-development"
gcp_region           = "us-central1"
env                  = "DEV"
log_level            = "INFO"
read_db_secret_name  = "readonly-arxiv-db-uri"
write_db_secret_name = "latexml_db_uri_psycopg2"