gcp_project_id       = "arxiv-development"
gcp_region           = "us-central1"
env                  = "DEV"
log_level            = "INFO"
read_db_secret_name  = "dev-db-6-readonly-uri"
write_db_secret_name = "stats-db-allprivileges-uri"