gcp_project_id                  = "arxiv-development"
gcp_region                      = "us-central1"
env                             = "DEV"
db_root_pw_secret_name          = "stats-db-root-pw"
db_admin_user_pw_secret_name    = "stats-db-admin-pw"
db_update_user_pw_secret_name   = "stats-db-insertupdate-pw"
db_readonly_user_pw_secret_name = "stats-db-readonly-pw"