gcp_project_id                  = "arxiv-production"
gcp_region                      = "us-central1"
env                             = "PROD"
db_root_pw_secret_name          = ""
db_admin_user_pw_secret_name    = ""
db_update_user_pw_secret_name   = ""
db_readonly_user_pw_secret_name = ""