gcp_project_id             = "arxiv-production"
gcp_region                 = "us-central1"
env                        = "PROD"
db_root_pw_secret_name     = ""
db_mig_user_pw_secret_name = ""
db_job_user_pw_secret_name = ""
db_app_user_pw_secret_name = ""