name: Format check and deploy aggregate-hourly-downloads

run-name: "Deploy aggregate-hourly-downloads - ${{ github.event.inputs.env }} - ${{ github.event.inputs.image_tag || github.sha }}"

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        type: string
        default: ""

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Format check
        run: terraform fmt -check

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    if: github.ref == 'refs/heads/main'
    needs: format-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          # Determine environment from inputs or GitHub environment
          if [ -n "${{ inputs.env }}" ]; then
            ENV_NAME="${{ inputs.env }}"
          else
            echo "Error: No environment specified"
            exit 1
          fi
          
          REGION="${{ vars.GCP_REGION || 'us-central1' }}"
          echo "ENVIRONMENT=$ENV_NAME" >> $GITHUB_ENV
          echo "REGION=$REGION" >> $GITHUB_ENV

          # Set project name and terraform bucket based on environment
          if [ "$ENV_NAME" = "production" ]; then
            echo "PROJECT_NAME=arxiv-production" >> $GITHUB_ENV
            echo "TERRAFORM_BUCKET=prod-arxiv-terraform-state" >> $GITHUB_ENV
            TERRAFORM_ARGS="-var-file=envs/prod.tfvars"
          elif [ "$ENV_NAME" = "development" ]; then
            echo "PROJECT_NAME=arxiv-development" >> $GITHUB_ENV
            echo "TERRAFORM_BUCKET=dev-arxiv-terraform-state" >> $GITHUB_ENV
            TERRAFORM_ARGS="-var-file=envs/dev.tfvars"
          else
            # For custom environments, use the environment name as project name
            echo "PROJECT_NAME=$ENV_NAME" >> $GITHUB_ENV
            echo "TERRAFORM_BUCKET=$ENV_NAME-arxiv-terraform-state" >> $GITHUB_ENV
            TERRAFORM_ARGS="-var-file=envs/dev.tfvars \
              -var=\"gcp_project_id=$ENV_NAME\" \
              -var=\"gcp_region=$REGION\""
          fi

          # Add commit sha to TERRAFORM_ARGS for all environments
          TERRAFORM_ARGS="$TERRAFORM_ARGS \
            -var=\"commit_sha=${{ github.sha }}\""

          echo "TERRAFORM_ARGS=$TERRAFORM_ARGS" >> $GITHUB_ENV

      - name: Zip function source
        run: |
          cd stats-functions/aggregate_hourly_downloads/src
          zip src.zip main.py entities.py models.py requirements.txt
          cp src.zip ../../../terraform/aggregate_hourly_downloads/

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v3
      #   with:
      #     workload_identity_provider: ${{ vars.PROVIDER_NAME }}
      #     service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Authenticate with project-specific Workload Identity
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.ARXIV_DEVELOPMENT_PROVIDER_NAME_SECRET }}
          service_account: ${{ secrets.ARXIV_DEVELOPMENT_SERVICE_ACCOUNT_SECRET }}
          # workload_identity_provider: ${{ env.PROVIDER_NAME }}
          # service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Impersonate project service account for deployment
        run: |
          # Set the project service account for deployment
          PROJECT_SA="deployment-sa@${{ env.PROJECT_NAME }}.iam.gserviceaccount.com"
          echo "Impersonating project service account: $PROJECT_SA"
          
          # Set impersonation for all gcloud commands
          echo "GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=$PROJECT_SA" >> $GITHUB_ENV
          
          # Also set it in gcloud config
          gcloud config set auth/impersonate_service_account $PROJECT_SA
          
          # Switch back to target project
          gcloud config set project ${{ env.PROJECT_NAME }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Configure terraform
        run: |
          echo "provider \"google\" {" > provider_override.tf
          echo "  project = \"${{ env.PROJECT_NAME }}\"" >> provider_override.tf
          echo "  region  = \"${{ vars.GCP_REGION }}\"" >> provider_override.tf
          echo "}" >> provider_override.tf
          
          echo "Terraform configuration:"
          echo "  Project: ${{ env.PROJECT_NAME }}"
          echo "  Region: ${{ vars.GCP_REGION }}"
          echo "  Commit SHA: ${{ github.sha }}"    
          echo "  TERRAFORM_ARGS: ${{ env.TERRAFORM_ARGS }}"
        working-directory: terraform/aggregate_hourly_downloads

      # - name: Initialize remote backend
      #   run: terraform init -backend-config="bucket=${{ vars.ENV_VAR }}-arxiv-terraform-state"
      #   working-directory: terraform/aggregate_hourly_downloads
      - name: Initialize remote backend
        run: terraform init -backend-config="bucket=${{ env.TERRAFORM_BUCKET }}"
        working-directory: terraform/aggregate_hourly_downloads

      # - name: Plan
      #   run: |
      #     echo "Running terraform plan..."
      #     terraform plan ${{ env.TERRAFORM_ARGS }}
      #   working-directory: terraform/aggregate_hourly_downloads

      # - name: Apply
      #   run: terraform apply -var-file=envs/${{ vars.ENV_VAR }}.tfvars -var="commit_sha=${{ github.sha }}" -auto-approve
      #   working-directory: terraform/aggregate_hourly_downloads

      - name: Apply
        run: |
          echo "Running terraform apply..."
          terraform apply ${{ env.TERRAFORM_ARGS }} \
            -auto-approve
        working-directory: terraform/aggregate_hourly_downloads
